# Generated by Django 5.1.15 on 2026-10-03 11:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(db_index=True, max_length=1000)),
                ('canonical_url', models.CharField(blank=True, default='', max_length=1000)),
                ('content_type', models.CharField(default='text/html', max_length=100)),
                ('http_status', models.IntegerField(default=200)),
                ('text_content', models.TextField(blank=True, default='', help_text='Sanitized visible text content')),
                ('raw_html_snippet', models.TextField(blank=True, default='', help_text='Sanitized snippet or structured markup, not giant blobs')),
                ('metadata_json', models.JSONField(blank=True, default=dict, help_text='Extracted JSON-LD, OpenGraph, or meta tags')),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('fetched_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='sources.source')),
                ('source_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='sources.sourcerun')),
            ],
            options={
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['content_hash'], name='crawling_ra_content_00cfd5_idx'), models.Index(fields=['url'], name='crawling_ra_url_ba0202_idx')],
            },
        ),
    ]
