# Generated by Django 5.1.15 on 2026-10-03 11:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query_text', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(blank=True, default='general', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('source_type', models.CharField(choices=[('rss', 'RSS / Atom Feed'), ('api', 'Public / Official API'), ('website', 'Permitted Website'), ('university', 'University Research Directory'), ('research_platform', 'Public Research Board'), ('custom', 'Custom Connector')], default='rss', max_length=30)),
                ('base_url', models.URLField(max_length=500)),
                ('feed_or_api_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('crawl_interval_seconds', models.IntegerField(default=3600, help_text='Interval in seconds between discovery runs')),
                ('rate_limit_rps', models.FloatField(default=1.0, help_text='Max requests per second')),
                ('compliance_notes', models.TextField(blank=True, default='Respects public robots.txt, public API terms, and reasonable request delays.')),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('failure_count', models.IntegerField(default=0)),
                ('avg_response_time_ms', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('failing', 'Failing'), ('disabled', 'Disabled')], default='idle', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SourceRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial')], db_index=True, default='running', max_length=20)),
                ('items_fetched', models.IntegerField(default=0)),
                ('items_parsed', models.IntegerField(default=0)),
                ('items_rejected', models.IntegerField(default=0)),
                ('items_accepted', models.IntegerField(default=0)),
                ('duplicate_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('response_time_ms', models.FloatField(default=0.0)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='sources.source')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawlFailure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=1000)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('failure_reason', models.CharField(max_length=255)),
                ('stack_trace', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failures', to='sources.source')),
                ('source_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failures', to='sources.sourcerun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
