# Generated by Django 5.1.15 on 2026-10-03 11:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crawling', '0001_initial'),
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIExtraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='mock', max_length=50)),
                ('model', models.CharField(default='gpt-4o-mini', max_length=100)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('latency_ms', models.FloatField(default=0.0)),
                ('raw_response', models.TextField(blank=True, default='')),
                ('parsed_output', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_extractions', to='opportunities.opportunity')),
                ('raw_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_extractions', to='crawling.rawdocument')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
