# Generated by Django 5.1.15 on 2026-10-03 11:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(help_text='ISO 2-letter country code: US or CA', max_length=2)),
                ('state_province', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('state_code', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('metro_area', models.CharField(blank=True, max_length=150, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('scope', models.CharField(choices=[('nationwide', 'Nationwide'), ('state', 'State'), ('province', 'Province'), ('territory', 'Territory'), ('region', 'Region'), ('city', 'City'), ('county', 'County'), ('metro_area', 'Metropolitan Area'), ('multi_state', 'Multi-State'), ('multi_province', 'Multi-Province'), ('remote', 'Remote'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=30)),
                ('is_us', models.BooleanField(db_index=True, default=False)),
                ('is_ca', models.BooleanField(db_index=True, default=False)),
                ('aliases', models.JSONField(blank=True, default=list, help_text='List of alternate names or regex keywords')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Geography',
                'verbose_name_plural': 'Geographies',
                'indexes': [models.Index(fields=['country', 'state_code'], name='geography_g_country_af2bca_idx'), models.Index(fields=['country', 'city'], name='geography_g_country_ed8f79_idx'), models.Index(fields=['scope', 'country'], name='geography_g_scope_32194b_idx')],
            },
        ),
    ]
