# Generated by Django 5.1.15 on 2026-10-03 11:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crawling', '0001_initial'),
        ('geography', '0001_initial'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('normalized_title', models.CharField(db_index=True, max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('study_type', models.CharField(choices=[('paid_survey', 'Paid Survey'), ('unpaid_survey', 'Unpaid Survey'), ('academic_survey', 'Academic Survey'), ('market_research', 'Market Research'), ('consumer_research', 'Consumer Research'), ('research_study', 'Research Study'), ('participant_recruitment', 'Participant Recruitment'), ('focus_group', 'Focus Group'), ('user_interview', 'User Interview'), ('ux_research', 'UX Research'), ('usability_test', 'Usability Test'), ('product_research', 'Product Research'), ('diary_study', 'Diary Study'), ('remote_study', 'Remote Study'), ('in_person_study', 'In-Person Study'), ('other', 'Other Research Study')], db_index=True, default='research_study', max_length=40)),
                ('source_url', models.CharField(max_length=1000)),
                ('canonical_url', models.CharField(blank=True, db_index=True, default='', max_length=1000)),
                ('application_url', models.CharField(blank=True, default='', max_length=1000)),
                ('organization', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('researcher_location', models.CharField(blank=True, default='', help_text='Location of researcher/org, separated from participant eligibility', max_length=255)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('published_at_timezone', models.CharField(blank=True, default='UTC', max_length=50)),
                ('published_date_precision', models.CharField(choices=[('exact_datetime', 'Exact Datetime'), ('exact_date', 'Exact Date'), ('relative_datetime', 'Relative Datetime'), ('relative_date', 'Relative Date'), ('approximate', 'Approximate'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('date_source', models.CharField(blank=True, default='unknown', max_length=100)),
                ('date_confidence', models.FloatField(default=0.0)),
                ('original_published_at', models.DateTimeField(blank=True, null=True)),
                ('repost_detected', models.BooleanField(default=False)),
                ('discovered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('reward_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reward_currency', models.CharField(default='USD', max_length=10)),
                ('reward_text', models.CharField(blank=True, default='', max_length=255)),
                ('reward_type', models.CharField(blank=True, default='', max_length=50)),
                ('is_paid', models.BooleanField(db_index=True, default=False)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('duration_text', models.CharField(blank=True, default='', max_length=100)),
                ('eligibility_text', models.TextField(blank=True, default='')),
                ('geography_status', models.CharField(choices=[('us_eligible', 'United States'), ('ca_eligible', 'Canada'), ('us_ca_eligible', 'US and Canada'), ('outside_target', 'Outside US/Canada'), ('unknown', 'Unknown Geography')], db_index=True, default='unknown', max_length=30)),
                ('participant_geo_confidence', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('discovered', 'Discovered'), ('processing', 'Processing'), ('verified', 'Verified'), ('eligible', 'Eligible'), ('excluded', 'Excluded'), ('duplicate', 'Duplicate'), ('uncertain', 'Uncertain'), ('expired', 'Expired'), ('failed', 'Failed')], db_index=True, default='discovered', max_length=30)),
                ('exclusion_reason', models.CharField(blank=True, default='', max_length=255)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('has_been_notified', models.BooleanField(db_index=True, default=False)),
                ('notification_count', models.IntegerField(default=0)),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('notified_channels', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canonical_opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='opportunities.opportunity')),
            ],
            options={
                'verbose_name_plural': 'Opportunities',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityGeography',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('nationwide', 'Nationwide'), ('state', 'State'), ('province', 'Province'), ('territory', 'Territory'), ('region', 'Region'), ('city', 'City'), ('county', 'County'), ('metro_area', 'Metropolitan Area'), ('multi_state', 'Multi-State'), ('multi_province', 'Multi-Province'), ('remote', 'Remote'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('is_explicit', models.BooleanField(default=True)),
                ('confidence', models.FloatField(default=1.0)),
                ('geography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_geographies', to='geography.geography')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geographies', to='opportunities.opportunity')),
            ],
            options={
                'verbose_name_plural': 'Opportunity Geographies',
            },
        ),
        migrations.CreateModel(
            name='OpportunitySource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_url', models.CharField(max_length=1000)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='opportunities.opportunity')),
                ('raw_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crawling.rawdocument')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_sources', to='sources.source')),
            ],
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['status', 'published_at'], name='opportuniti_status_d426cb_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['geography_status', 'is_paid'], name='opportuniti_geograp_7162e5_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['has_been_notified', 'status'], name='opportuniti_has_bee_aca0b2_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['content_hash'], name='opportuniti_content_6ffcaf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='opportunitysource',
            unique_together={('opportunity', 'source_url')},
        ),
    ]
